### ISSUE TITLE
`M_NOT_FOUND: Event not found` when trying to get .name on some joined-room

### ISSUE THREAD

**Issue by AlexDaniel** [matiaslina/perl6-matrix-client#13] opened 2018-08-07 13:55 UTC
```
M_NOT_FOUND: Event not found.
  in method handle-error at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/E7751191976204E9D21C92A2486C980334A2E4CB (Matrix::Client::Requester) line 20
  in method get at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/E7751191976204E9D21C92A2486C980334A2E4CB (Matrix::Client::Requester) line 36
  in method get-name at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/6A5C5D7AF9F46FE814F0C6B3BD7E3297E85ABE4B (Matrix::Client::Room) line 24
  in method name at /home/alex/.rakudobrew/moar-master/install/share/perl6/site/sources/6A5C5D7AF9F46FE814F0C6B3BD7E3297E85ABE4B (Matrix::Client::Room) line 33
```

The code is basically:
```
say $client.joined-rooms».name;
```

Not sure why it happens, but I think it's because the room has no name.

**Comment by matiaslina** [comment] 2018-08-07 23:03
Right… That's because the endpoint that queries the room name returns `M_NOT_FOUND` if there's no event (`m.room.name` in this case ) sent to the server.

I guess the best solution is to catch that error for the name, and return an empty string. A workaround until I make that change is something like this:

```perl6
> $client.joined-rooms».map: { try { .name } // 'Unknown' }
((The Grand Duke Pub) (Unknown) (Unknown) (The Grand Duke Pub))
```

**Comment by matiaslina** [comment] 2018-08-09 23:26
I'm closing this for now. I've tested it and is working as intended (returning `''` on missing name).

**Closed by matiaslina** 2018-08-09 23:26 UTC
Labels: enhancement
